optimizer: PCD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true 
batchsize: 128
data_proto: "PLP_rbm2_LAST/data.pbtxt"
eval_after: 5000
checkpoint_after: 20000
checkpoint_directory: "/data1/ningzhang/audio_eating_2/npFeatures/All/LOPO_2_Multimodal_clean/models/withMS"
data_proto_prefix: "/data1/ningzhang/audio_eating_2/npFeatures/All/LOPO_2_Multimodal_clean/reps/withMS"
verbose: false
randomize: true
