name: "MFCC_Energy_rbm3"
model_type: DBM
hyperparams {
  base_epsilon: 0.01
  epsilon_decay : INVERSE_T
  epsilon_decay_half_life : 10000
  initial_momentum : 0.5
  final_momentum : 0.9
  momentum_change_steps : 10000
  apply_l2_decay: true
  l2_decay: 0.001
  activation: LOGISTIC
  mf_steps: 1
  gibbs_steps: 5
  start_step_up_cd_after: 20000
  step_up_cd_after: 20000
}

layer {
  name: "MFCC_Energy_hidden2"
  dimensions: 1536
  is_input: true
  param {
    name: "bias"
    initialization: CONSTANT
  }
  loss_function: SQUARED_LOSS
  data_field {
    train: "MFCC_Energy_hidden2_train"
    validation: "MFCC_Energy_hidden2_validation"
    test: "MFCC_Energy_hidden2_test"
  }
  performance_stats {
    compute_error: true
  }
  hyperparams {
    sparsity : false
    apply_l2_decay: false
    enable_display: false
    #dropout: true
  }
}

layer {
  name: "MFCC_Energy_hidden3"
  dimensions: 1280
  param {
    name: "bias"
    initialization: CONSTANT
  }
  hyperparams {
    apply_l2_decay: false
    enable_display: false
  }
}

edge {
  node1: "MFCC_Energy_hidden2"
  node2: "MFCC_Energy_hidden3"
  directed: false
  up_factor: 1.0
  down_factor: 2.0
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma : 1.0
  }
}
