optimizer : CD
stopcondition {
  all_processed: false
  steps: 5000
}
train: true 
batchsize: 128
data_proto: "data_withoutMS.pbtxt"
eval_after: 5000
checkpoint_after: 5000
checkpoint_directory: "/data1/ningzhang/audio_eating_2/npFeatures/All/LOPO_1_Multimodal/models/withoutMS"
data_proto_prefix: "/data1/ningzhang/audio_eating_2/npFeatures/All/LOPO_1_Multimodal"
verbose: false
randomize: true
